### ISSUE TITLE
Unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/mlops-on-gcp#62]
It seems that the follow script to create a Kubeflow instance is not working anymore on GCP:
https://github.com/GoogleCloudPlatform/mlops-on-gcp/tree/master/examples/mlops-env-on-gcp/provisioning-kfp

The issue is in the install.sh script and I am getting:
`Unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta2"`

current and not working
```
# Deploy KFP to the cluster
export PIPELINE_VERSION=0.2.5
kustomize build \
    github.com/kubeflow/pipelines/manifests/kustomize/base/crds/?ref=$PIPELINE_VERSION | kubectl apply -f -
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kustomize build . | kubectl apply -f -
```
working solution
```
# Deploy KFP to the cluster
export PIPELINE_VERSION=1.0.4
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"
```

I am not an expert so I don't do a PR. Just highlighting what was working for me in case it can help other users.

**Comment by kornelregius** [comment]
@tarrade Is the rest of instructions, examples worked well in your installation with version 1.0.4?

**Comment by tarrade** [comment]
@kornelregius yes for the installation script. Then I had no issue with my custom Kubeflow cluster.  Now I got some issue with the script to destroy the Kubeflow cluster and other stuff created with the creation script. Now I didn't have time to investigate and fix the issue so I deleted all stuff manually.

**Comment by tarrade** [comment]
way too old and now with Vertex managed pipeline it is not needed to create your custom Kubeflow cluster. Closing
