### ISSUE TITLE
lab-02-kfp-pipeline: container build error

### ISSUE THREAD

**Issue by BenoitDherin** [GoogleCloudPlatform/mlops-on-gcp#7]
In the notebook [lab-02](https://github.com/GoogleCloudPlatform/mlops-on-gcp/blob/master/workshops/kfp-caip-sklearn/lab-02-kfp-pipeline/lab-02.ipynb), the container build

![image](https://user-images.githubusercontent.com/5290305/79984362-56dec180-84a9-11ea-98df-4ea3456ba1f7.png)

produces the following error

![image](https://user-images.githubusercontent.com/5290305/79984598-ae7d2d00-84a9-11ea-83cf-5eb52f391e9b.png)

The build succeeds though.

**Comment by jarokaz** [comment]
You will almost always have these kind of errors due to using a deep learning container as a base. You can ignore them.
